# Generated by Django 3.2.6 on 2021-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_Nombre', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=500)),
                ('fotejes', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Extreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_Nombree', models.CharField(max_length=110)),
                ('ext_Idioma', models.CharField(max_length=26)),
                ('ext_descripcion', models.CharField(max_length=500)),
                ('fecha_estreno', models.DateField()),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_genero', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=30)),
                ('fil_Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_Nombre', models.CharField(max_length=500)),
                ('rec_idioma', models.CharField(max_length=30)),
                ('rec_calidad', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=500)),
                ('imga', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('idioma', models.CharField(max_length=40)),
                ('calidad', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('Ver_online', models.CharField(max_length=400)),
                ('descargas', models.ManyToManyField(blank=True, null=True, to='app.Descarga')),
                ('filtros', models.ManyToManyField(blank=True, null=True, to='app.Filtro')),
                ('generos', models.ManyToManyField(blank=True, null=True, to='app.Genero')),
            ],
        ),
    ]
