# Generated by Django 3.2.6 on 2021-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_driveruser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveruser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
